spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      rule: random

    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            # A predicate that matches requests to the path '/products/**'
            # and forwards them to the product-service.
            - Path=/user-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

