server:
  port: 8083

spring:
  application:
    name: parking-service

  config:
    import: optional:configserver:http://localhost:8888/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/